Plotting: Plot time axis as phi (epiboly progress) when possible
When plotting vs time as the x-axis, instead use epiboly
progress (leading edge mean phi) as a proxy for time.
This is like plotting vs. embryonic stage. (Almost!)

Avoids the time distortion caused by the fact that epiboly
slows down as the sim proceeds.

Exception: when run_balanced_force_control is set, since
EVL will not advance (assuming yolk_cortical_tension vs.
external_force are set correctly), you cannot plot vs. epiboly
progress, so in that case, stick with plotting v. time.